#' Generate an encoding key which is used for encoding and decoding strings to pass the R parser
#'
#' @return A list containing the encoding key, with 'input' specifying the characters to be encoded
#' and 'output' specifying their corresponding encoded values.
#' @noRd
.getEncodeKey <- function() {
  encode_list <- list(
    input = c("list", "(", ")", "\"", ",", " ", "c", ":", "!", "&", "|"),
    output = c("$LIST$", "$LB$", "$RB$", "$QUOTE$", "$COMMA$", "$SPACE$", "$C$", "$COLON$", "$EXCL$", "$AND$", "$OR$")
  )
  return(encode_list)
}

#' Decode a string using the provided encoding key.
#'
#' @param input_string The encoded string passed through the R parser.
#' @param encode_key The encoding key generated by '.getEncodeKey()'.
#' @return The decoded string.
#' @importFrom stringr str_replace_all fixed
#' @noRd
.decode_tidy_eval <- function(input_string, encode_key){
  encode_vec <- setNames(encode_key$input, encode_key$output)
  output_string <- str_replace_all(input_string, fixed(encode_vec))
  return(output_string)
}

#' Generate a string containing the arguments for a Tidyverse function.
#'
#' @param .data Character describing the data object to be manipulated.
#' @param fun Character describing the Tidyverse function to be executed.
#' @param tidy_select_args The arguments for the Tidyverse function passed through the R parser.
#' @return A string representing the Tidyverse function and its arguments.
#' @noRd
.make_tidyselect_arg <- function(.data, fun, tidy_select_args){
  tidy_arg_string <- paste0(.data, " %>% dplyr::", fun, "(", tidy_select_args, ")")
  return(tidy_arg_string)
}

#' Execute a Tidyverse function on a data object with specified arguments.
#'
#' @param .data Character describing the data object to be manipulated.
#' @param fun Character describing the Tidyverse function to be executed.
#' @param tidy_select_args The arguments for the Tidyverse function passed through the R parser.
#' @return The result of executing the Tidyverse function on the data object.
#' @importFrom rlang parse_expr
#' @importFrom rlang eval_tidy
#' @noRd
.execute_tidyverse_function <- function(.data, fun, tidy_select_args){
  tidy_string <- .make_tidyselect_arg(.data, fun, tidy_select_args)
  string_as_expr <- rlang::parse_expr(tidy_string)
  object_out <- eval_tidy(string_as_expr)
  return(object_out)
}
